# .github/workflows/actualizar_agenda.yml

name: Actualizar Agenda Deportiva Automáticamente

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar script de scraping y generación de HTML
        run: python uno_solo.py

      - name: Renombrar archivo de salida a index.html
        run: mv agenda_deportiva.html index.html
        
      # 6. Preparar el artefacto para GitHub Pages
      - name: Subir artefacto para GitHub Pages
        uses: actions/upload-pages-artifact@v3 # <-- VERSIÓN ACTUALIZADA

      # 7. Desplegar en GitHub Pages
      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # <-- VERSIÓN ACTUALIZADA
